# Generated by Django 4.1.5 on 2023-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('capital_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
